### ISSUE TITLE
Exception with Python 2.6

### ISSUE THREAD

**Issue by jezdez** [rubik/pyg#35]
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyg", line 9, in <module>
    load_entry_point('pyg==0.4', 'console_scripts', 'pyg')()
  File "pyg/__init__.py", line 19, in main

  File "/Library/Python/2.6/site-packages/argh/helpers.py", line 304, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/Library/Python/2.6/site-packages/argh/helpers.py", line 205, in dispatch
    for line in lines:
  File "/Library/Python/2.6/site-packages/argh/helpers.py", line 281, in _execute_command
    for line in result:
  File "/Library/Python/2.6/site-packages/argh/helpers.py", line 264, in _call
    result = args.function(args)
  File "/Library/Python/2.6/site-packages/pyg/parser/parser.py", line 29, in install
    opts.install_func(args)
  File "/Library/Python/2.6/site-packages/pyg/parser/_opts.py", line 95, in install_func
    _install_package_from_name(package)
  File "/Library/Python/2.6/site-packages/pyg/parser/_opts.py", line 69, in _install_package_from_name
    return Installer(package).install()
  File "/Library/Python/2.6/site-packages/pyg/inst.py", line 67, in install
    r.install()
  File "/Library/Python/2.6/site-packages/pyg/req.py", line 115, in install
    self._download_and_install(url, name, p.name, hash)
  File "/Library/Python/2.6/site-packages/pyg/req.py", line 100, in _download_and_install
    installer.install()
  File "/Library/Python/2.6/site-packages/pyg/types.py", line 234, in install
    Dir(fullpath, self.name, tempdir, self.reqset).install()
  File "/Library/Python/2.6/site-packages/pyg/types.py", line 199, in install
    call_setup(self.path, ['egg_info', '--egg-base', self.tempdir])
  File "/Library/Python/2.6/site-packages/pyg/utils.py", line 89, in call_setup
    return call_subprocess(args + a, stdout=stdout, stderr=stderr)
  File "/Library/Python/2.6/site-packages/pyg/utils.py", line 74, in call_subprocess
    output = subprocess.check_output(args, stderr=subprocess.STDOUT)
AttributeError: 'module' object has no attribute 'check_output'
```

**Comment by rubik** [comment]
WoW! You tried it!! Thank you! Currently Pyg best fits with Python 2.7 but should work with Python 2.6 too... I didn't notice that subprocess.check_output was added in Python 2.7! I fix it now.

**Comment by rubik** [comment]
Thank you! It should work now. The new release is on PyPI. (`0.4.1`)
